# Setup
title: "LOG"
tagline: "기록이 실력으로"
description: "기록 블로그"
url: "https://0626na.github.io"
# baseurl: ""
paginate: 5
permalink: pretty
lsi: true

# About/contact
author:
  name: SUKJIN HAN
  url: https://github.com/0626na
  email: 0626na@gmail.com

# Gems
plugins:
  - jekyll-paginate
# Custom vars
#version: 4.3.2
#google_analytics_id: #UA-XXXX-Y
